<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\CallData */

$this->title = $model->RowID;
$this->params['breadcrumbs'][] = ['label' => 'Call Data', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="call-data-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <!--<?//= Html::a('Update', ['update', 'id' => $model->RowID], ['class' => 'btn btn-primary']) ?>
        <?//= Html::a('Delete', ['delete', 'id' => $model->RowID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>-->
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'RowID',
            'CaseID',
            'UserID',
            'MediaID',
            'CallID',
            'ScriptID',
            'StartedAt',
            'EndedAt',
            'Duration',
            'ScriptVersion',
            'AgentID',
            'AgentUserName',
            'DomainCode',
            'DispositionCode',
            'Sale',
            'CallType',
            'AltPhoneNumber',
            'BestTime',
            'ServiceType',
            'BillingAddress1',
            'BillingAddress2',
            'BillingAdrSame',
            'BillingCity',
            'BillingFirstName',
            'BillingLastName',
            'BillingState',
            'BillingZip',
            'CBDay',
            'CBPhoneNumber',
            'CBTime',
            'CCExpMonth',
            'CCExpYear',
            'CCFirstName',
            'CCLastName',
            'CCNumber',
            'CCType',
            'CCTypeLong',
            'Comments',
            'DialupAccess',
            'DNIS',
            'EmailAddress:email',
            'EmailAddress2:email',
            'ExpRepairType',
            'FlexAmount',
            'FlexDiscount',
            'GenerateQuote',
            'InstallerNotes',
            'InstallOption',
            'MaintainOption',
            'NoOrderReason',
            'NumLocations',
            'NumStaticIP',
            'OriginalANI',
            'OwnProperty',
            'PaymentOption',
            'PhoneNumber',
            'PlaceOrder',
            'PlanName',
            'QuoteID',
            'ServiceAddress1',
            'ServiceAddress2',
            'ServiceCity',
            'ServiceFirstName',
            'ServiceLastName',
            'ServicePlan',
            'ServiceState',
            'ServiceZip',
            'SomeHeavyUsage',
            'StandardBrowsing',
            'StaticIPMention',
            'TransactionID',
            'TransactionTime',
            'CancelledOrder',
            'ExpectingMove',
            'P10NoSlots',
            'ResID',
            'BypassP10',
            'OrderID',
            'ModTransactionID',
            'OriginalCallID',
            'HighSpeedArea',
            'CheckEligible',
            'ServicePlanType',
            'Lowfill',
            'AfbCall',
            'Afb',
            'MemberID',
            'AdID',
            'TicketID',
            'HowFound',
            'CreateDate',
            'ContactID',
            'MediaType',
            'ExpeditedInstall',
            'RemoteMaintenance4',
            'RemoteMaintenance3',
            'DeIce',
            'Data',
            'Antenna',
            'AntiIce',
            'OrderRespCode',
            'OrderRespMsg',
            'LastUpdate',
            'OutboundContactID',
            'ZoneAlarm',
            'PSE',
            'MailCode',
            'Reserve3',
            'VoIP',
            'LeaseFail',
            'OfferedProducts',
            'LeaseFailPIM',
            'LeaseFailMessage',
            'VoIPEligible',
            'OfferID',
            'Reserve4',
            'POAccepted',
            'CCSource',
            'ContactConsent',
            'WelcomeFreeForm',
            'Company',
            'SWVoIP',
            'SAN',
            'DSSStatus',
            'Activated',
            'Churn1',
            'Churn2',
            'Churn3',
            'DSSCharge',
            'SpiceCharge',
            'Connection',
            'ServiceZip5',
            'OneDayCancel',
            'OfferServices',
            'CheckServices',
            'VEMPim',
            'NewEmailAttempt:email',
            'VerifyEmailSpelling:email',
            'ConfirmEmail:email',
            'VEMAttempts',
            'VerizonCustomer',
            'RAFShortCode',
            'ORDContactID',
            'SelectedInstallDate',
            'Churn4',
            'DateInstalled:ntext',
            'RAFSelected',
            'GamingDisc',
            'StreamingDisc',
            'VoiceDisc',
            'BonusBytesDisc',
            'SpeedDisc',
            'CreditCheckDisc',
            'ExpRepairReviewed',
            'ExpRepairConsent',
            'ExpRepairSold',
            'PCEReviewed',
            'PCEConsent',
            'PCESold',
            'ZAReviewed',
            'ZAConsent',
            'ZASold',
            'VoIPReviewed',
            'VoIPConsent',
            'VoIPSold',
            'WirelessDisc',
            'ChargesExplained',
            'TNCVerbatim',
            'AllowanceDisc',
            'WirelessRouter',
            'TelephonyDNIS',
            'DatesAvailable',
            'ScheduleAttempted',
            'SSAdmin',
            'BIN',
            'CreditReport',
            'SwitchToConsumer',
            'SwitchToConsumerReason:ntext',
            'GoodFit',
            'HowDidYouHear',
            'FedExOveride',
            'Reserve1',
            'Reserve2',
            'NortonReviewed',
            'Norton',
            'NortonConsent',
            'NortonSold',
            'RowDate',
            'StaticIP',
            'Reserve5',
            'Reserve6',
            'Beam',
            'BeamType',
        ],
    ]) ?>

</div>
